[package]
name = "smve_internal"
version = "0.1.0"
edition = "2021"

[dependencies]
smve_asset_pack = { path = "../smve_asset_pack" }
smve_render = { path = "../smve_render" }

[lints]
workspace = true
