[package]
name = "smve_asset_pack"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
blake3 = "1.5"
ignore = "0.4"
tempfile = "3.10"
log = "0.4"
thiserror = "1.0"
indexmap = "2.2"
lz4 = "1.26"
toml = { version = "0.8", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
downcast-rs = "1.2"
merge = { git = "https://github.com/ItsSunnyMonster/merge.git", branch = "versions/0.1.1" }
glob = "0.3"
serde-tuple-vec-map = "1.0"
walkdir = "2.5.0"
pathdiff = "0.2.1"

[dev-dependencies]
env_logger = "0.11.5"
