[package]
name = "smve_asset_pack_compiler"
version = "0.1.0"
edition = "2021"
description = "A simple CLI used to compiling assets into an asset pack file."

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
smve_asset_pack = { path = "../smve_asset_pack" }
env_logger = "0.11.5"

[lints]
workspace = true
